# Generated by Django 3.1.1 on 2020-10-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_videocomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('grade', models.IntegerField(blank=True)),
                ('video', models.FileField(upload_to='files')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher_detail')),
            ],
        ),
    ]
