# Generated by Django 3.1.1 on 2020-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(default='0')),
            ],
        ),
    ]
