# Generated by Django 3.1.1 on 2020-10-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('grade', models.IntegerField(default='0')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
