# Generated by Django 3.1.1 on 2020-10-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201008_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='fname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='detail',
            name='lname',
            field=models.CharField(default='', max_length=15),
        ),
    ]
