# Generated by Django 3.1.1 on 2020-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, default='MicrosoftTeams-image.png', null=True, upload_to=''),
        ),
    ]
