# Generated by Django 3.1.1 on 2020-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201025_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='email',
            field=models.EmailField(blank=True, default='ab@gmail.com', max_length=20),
        ),
    ]
